language: node_js
node_js:
  - "12"
notifications:
  email: false
before_script:
  - npm install -g abaplint
  - abaplint -v
script:
  - abaplint
branches:
  only: 
    - master
deploy:
  - provider: script
    script: ./ci/deploy-release-tag.sh
    on:
      branch: master
      tags: false
env:
  global:
    - DEPLOY_VERSION_FILE="src/zif_mockup_loader_constants.intf.abap"
    - DEPLOY_VERSION_CONST="version"
    - ENCRYPTION_LABEL="885bbce9f605"
